### ISSUE TITLE
last added rather than modified/created?

### ISSUE THREAD

**Issue by ghost** [raguay/MyLaunchBarActions#1]
Right now the action is looking for the most recently modified or created file in the downloads folder which works great most of the time. I have a hazel rule that frequently moves files I'm working with into the downloads folder, because these are older files moved into the downloads folder, this action doesn't pick it up. For me,  this action would ideally grab the most recently added file. Is this possible?

**Comment by raguay** [comment]
Hi,

I just added the Quick Load Options action that allows you to select which way to order (latest modified or latest added). Let me know if this covers your workflow properly.

**Comment by ghost** [comment]
Great update, thanks Raguay, it does exactly what I was looking for.

**Comment by raguay** [comment]
Wow, you got it fast. I am glad it fits your usage. Please let me know if
you can think of any other improvements.

**Comment by ghost** [comment]
:) I was checking email and the github notification popped up. 

I'll let you know if anything else comes to mind! Thanks again.
