### ISSUE TITLE
PDF of Help File mentioned in Quiver Snippets Action

### ISSUE THREAD

**Issue by JMichaelTX** [raguay/MyLaunchBarActions#2]
### [Launch Bar Quiver Snippets Action Help.pdf](https://github.com/raguay/MyLaunchBarActions/files/520625/Launch.Bar.Quiver.Snippets.Action.Help.pdf)

>  Please refer to the help file for more information.

The "help file" is not really a file.  It is a Quiver Notebook that gets installed.
Obviously you can't see the "help file" you really need to install stuff until AFTER installation!

**Comment by raguay** [comment]
Thanks. Sorry for the confusion.
